### ISSUE TITLE
StarkMenu

### ISSUE THREAD

**Issue by ghost** [B00merang-Project/Windows-Longhorn#1]

**Comment by cinnamoner** [comment]
@Elbullazul 
For Fair Use Only.
![20160611_004101](https://cloud.githubusercontent.com/assets/15638605/15981699/0c0cafee-2f82-11e6-9314-05b8ebf336c6.jpg)

**Comment by cinnamoner** [comment]
![20160611_004131](https://cloud.githubusercontent.com/assets/15638605/15981740/a3b2b32a-2f82-11e6-9165-742224960d8d.jpg)
For Fair Use Only.

**Comment by cinnamoner** [comment]
For Fair Use Only.
![20160611_004227](https://cloud.githubusercontent.com/assets/15638605/15981788/46f0863e-2f83-11e6-9a0c-5e97f09cc5f7.jpg)

**Comment by cinnamoner** [comment]
@Elbullazul 
Cute buttons, hmmm?

**Comment by dominichayesferen** [comment]
Yeah... :)

**Comment by cinnamoner** [comment]
@feren 
I'm gald you like 'em :)

**Comment by cinnamoner** [comment]
@Elbullazul 
Where is the lord of the house?

**Comment by Elbullazul** [comment]
He was out on vacation  :/

Looks great,  but we still have to wait for the classes niko promised

**Comment by cinnamoner** [comment]
@Elbullazul 
Good. Thank you. It's just a matter of time then.

**Comment by cinnamoner** [comment]
@Elbullazul 
Okay, these are the navigation buttons I would enjoy in the Vista theme (Redmond repo):

**Comment by cinnamoner** [comment]
For Fair Use Only
![20160614_164014](https://cloud.githubusercontent.com/assets/15638605/16048422/aa4f06a2-325c-11e6-8a44-891b31460ef0.jpg)

**Comment by cinnamoner** [comment]
Okay, and this is the window border & buttons I favor for the Vista theme (Redmond repo):

**Comment by cinnamoner** [comment]
For Fair Use Only

**Comment by cinnamoner** [comment]
Coming soon ...

**Comment by cinnamoner** [comment]
For Fair Use Only 
![20160614_164443](https://cloud.githubusercontent.com/assets/15638605/16050316/dcb0bf9e-3263-11e6-9b61-97548caa040d.jpg)

**Comment by cinnamoner** [comment]
Proof of this look having had appeared in Vista first has already been delivered on the off topic thread (10 repo).

**Comment by cinnamoner** [comment]
@Elbullazul 
So what do you think?

**Comment by Elbullazul** [comment]
@cinnamoner wikipedia confirms this. My bad, you win this time :smile:

**Comment by cinnamoner** [comment]
@Elbullazul
I have never considered to go into any competition with you.
Please, check the the thread referenced on this one 'cause NicoKrause seems puzzled. I can't get any clearer than that.

**Comment by Elbullazul** [comment]
@cinnamoner or he's just offline. Leave it like that, he'll understand when he has time to analyse everything

**Comment by cinnamoner** [comment]
@Elbullazul 
Sure thing.
