### ISSUE TITLE
Jade Problems

### ISSUE THREAD

**Issue by dominichayesferen** [B00merang-Project/Windows-Longhorn#13]
1. Firstly, there's no more transparent start button logo for the Jade theme now on the (non-customisable Start Button) theme
2. Right now, inactive windows now have black text unlike beforehand on Window List which looks kinda bad
3. Could you do an Arc with the GTK and make the window buttons in Headerbars copies of the images for the titlebars?
4. Other than that, looks really slick, great job!!

Things begging to be fixed in action:
![screenshot from 2016-09-26 20-27-21](https://cloud.githubusercontent.com/assets/11057934/18848910/70de0ea4-8428-11e6-954c-d466a0be4dd2.png)

**Comment by Elbullazul** [comment]
button: fixed, coming soon...

can't reproduce the 2nd one, can you try to fix it yourself first?

**Comment by dominichayesferen** [comment]
@Elbullazul 2nd one is in the picture

**Comment by Elbullazul** [comment]
yes, but I don't get black text on my system

can you check the window-list class and see if there's any black? on my copy I don't

**Comment by dominichayesferen** [comment]
@Elbullazul I'll look later
Do you want to do that suggestion for the headerbar buttons to make it look more consistent?

**Comment by Elbullazul** [comment]
I will, but I need to make it work for 3.18 first

**Comment by cinnamoner** [comment]
It has taken some time but that's wat I wanted. Order. Hahaha.

**Comment by dominichayesferen** [comment]
You're right, doesn't happen on Stable

**Comment by Elbullazul** [comment]
[Windows Longhorn Jade.tar.gz](https://github.com/Elbullazul/Longhorn-Collaboration/files/498843/Windows.Longhorn.Jade.tar.gz)
3.18 compatible file. Will update the repo later, I'm on a VM

**Comment by Elbullazul** [comment]
![virtualbox_linux mint 18_28_09_2016_13_38_40](https://cloud.githubusercontent.com/assets/15310985/18925179/da848320-8580-11e6-84b4-53dff69e0e1e.png)

**Comment by dominichayesferen** [comment]
What happened to the perfectly working start-here image on CSB?

**Comment by Elbullazul** [comment]
I'm on a VM, so I don't have the latest version (?)

I was focusing on GTK, not cinnamon

**Comment by dominichayesferen** [comment]
@Elbullazul Oh ok, any progress on the Headerbar (Arc-like) use of images only for titlebar buttons in headerbars?

**Comment by Elbullazul** [comment]
header-bar fixed as shown below:
![](https://cloud.githubusercontent.com/assets/15310985/18957817/850ea78c-862e-11e6-8ad2-d64c2224eb32.png)

Jade almost ready, just need to fix the .popup .menuitem class background and the toolbar buttons with the new gradient and Jade is ready for release! :D

**Comment by dominichayesferen** [comment]
@Elbullazul Just remember the left/right edge gradients too. ;)

**Comment by Elbullazul** [comment]
yeah, found the code in @bluedxca93's code for the arrow items

**Comment by dominichayesferen** [comment]
@Elbullazul Ok, that combined with the icon set with newer back and forward scalables will look freaking neat as hell! :D

**Comment by cinnamoner** [comment]
@feren Absolutely gorgeous little theme, I agree.

**Comment by cinnamoner** [comment]
@Elbullazul Perhaps a different zoom slider, this time round, hmmm?

**Comment by dominichayesferen** [comment]
New icons are coming your way guys
Navigation ones mostly

**Comment by Elbullazul** [comment]
@cinnamoner suggestions?

**Comment by feren** [comment]
@Elbullazul The slider of Jade (tommorow)

**Comment by cinnamoner** [comment]
> suggestions?

@Elbullazul @feren I don't really know how the slider in the original looks like, but methinks one should try emulating the original as closely as possible. I'll look into it. Jade is important to me so I'll study it thoroughly and feed some suggestions. My first one: like W10, Jade should be complemented with an icon pack of its own but I guess that one is already comming. This Windows is truly a Windows, no question about it. What makes it attractive aside from its beauty it's that it had never made it to the market. It's a never seen but still true kinda thing.

**Comment by dominichayesferen** [comment]
It looks like the resources on this:
https://github.com/Elbullazul/Longhorn-Collaboration/issues/8

**Comment by cinnamoner** [comment]
@feren I really want this theme (Jade) to be a masterpiece. The best of them all.

**Comment by dominichayesferen** [comment]
@Elbullazul About the Jade theme
1. The maximize/restore button has no hover or pressed image(s) on headerbars
2. You may want to implement the resources (the smallest sizes if possible) from https://github.com/Elbullazul/Longhorn-Collaboration/issues/8#issuecomment-250912562 and https://github.com/Elbullazul/Longhorn-Collaboration/issues/8#issuecomment-250789086
3. Also, if possible, MAKE ALL THE NEMO BUTTONS WIDE MAYBE?

**Comment by Elbullazul** [comment]
you mean longer on the sides?

**Comment by dominichayesferen** [comment]
I mean making the width longer...

**Comment by dominichayesferen** [comment]
@Elbullazul 
https://github.com/Elbullazul/Longhorn-Collaboration/issues/8#issuecomment-250912894
https://github.com/Elbullazul/Longhorn-Collaboration/issues/8#issuecomment-250912562
https://github.com/Elbullazul/Longhorn-Collaboration/issues/8#issuecomment-250789086

**Comment by dominichayesferen** [comment]
@Elbullazul I noticed a new bug with Jade's buttons (refer to 'Cancel' button):
![screenshot from 2016-10-07 17-05-17](https://cloud.githubusercontent.com/assets/11057934/19198776/5fd92d92-8cb0-11e6-98dd-3cb462bb8c76.png)

**Comment by Elbullazul** [comment]
no problem, will check this out

BTW I decided to use gradients rather than images because doing so breaks comboboxes and entry buttons, as well as toolbuttons

**Comment by dominichayesferen** [comment]
Silence has arose. DeviantArt has just lost a Windows-theming legend for real. D':
http://neiio.deviantart.com/status/5175661

**Comment by Elbullazul** [comment]
he made windows themes for windows, right?

nice artwork, sad he passed away, sounds like he wasn't old at all

**Comment by dominichayesferen** [comment]
He made all kinds of themes for Windows. :(

**Comment by ghost** [comment]
well most windows skinners are retired or students afaik. but that
doesnt make them really old.

yes gradients are faster and more stable than images. but i just like
to use them.

**Comment by dominichayesferen** [comment]
Hmm, where's everyone??

**Comment by ghost** [comment]
snappy packages are currently unable to load png files.
perhaps this will be fixed in mate16.10 and other.

**Comment by cinnamoner** [comment]
@feren I'm here, as always :) Anything that troubles you, or some insights?

**Comment by cinnamoner** [comment]
@feren I still don't know which distro to settle for. All have flaws. An Firefox too has dropped support for Vista. Firefox won't update. Fresh install of the latest version is the only solution. 49.0.1.

**Comment by cinnamoner** [comment]
Neon is pretty good but Discover is still sluggish and has slight issues. Ubuntu Mate is fast and functional but is so old school. Cinnamon would be OK but not Mint. They have driven their flagship into the fence. And I don't dare to mess with Arch. Or its offshoots. As much as I kinda like the terminal, we're in 2016. An OS without graphical software centre is not conceivable. I would go for Windows 10 but they are overdoing it with gathering and one has no control over the damn thing.

**Comment by cinnamoner** [comment]
@Elbullazul just put a thumb down whenever you want a post deleted. Just to maintain order.

**Comment by cinnamoner** [comment]
@bluedxca93 If I could only have gnomenu on Mate, that would be fantastic. I don't understand the cairo dock association. What the hack is that. I know cairo but I don't understand how it connects with gnomenu.

**Comment by cinnamoner** [comment]
The untimely passaway is saddening. Remember? I've been saying things about time you don't still understand.

**Comment by dominichayesferen** [comment]
@cinnamoner I'd say Haze OS, but, that's dead now...
Maybe try Ubuntu and then add a Cinnamon 3.0 PPA to it, install Cinnamon and then uninstall 'unity'?

**Comment by dominichayesferen** [comment]
@cinnamoner Yeah, we've lost a legend, my thoughts are with Mallory and the rest of his family...

**Comment by cinnamoner** [comment]
Fun fact: Jade is reminiscent of my fridge. Looks like curved metal. I love my fridge though.

**Comment by dominichayesferen** [comment]
@cinnamoner lol, that irony though

**Comment by cinnamoner** [comment]
@feren Accident or illness? What was it?

**Comment by dominichayesferen** [comment]
@cinnamoner He firstly said he was ill, he said that he was going to undergo surgery that'd hopefully fix it... Then came the notification, it read this:
"I  don't know how to put this into words through the tears, this has been the shittiest day of my life...I'll try to keep this brief as I'm breaking down.  My Dad, Jamie Green or neiio as most of you know him has passed away early this morning.  **There were complications with the surgery that's all we know for sure.**  He left me detailed instructions on what to do if this were to happen but I'm too exhausted and in disbelief to follow all his requests at the moment.  **He was much too young to be taken away from my sister and I**.  He had his demons but he was the best dad ever and I don't know how I'm going to manage with his passing.  Thank you for all your prayers and wishes, I don't really know what else to say right now...**I'm crushed**.  I just wanted to pass this on as many of you he considered to be great friends and he loved this site so much it was a great passion of his...I will continue to look after his profile and peek in from time to time.
With much sadness...
Mallory...
dark-necessities (this is the oldest daughter of Jamie Green)
P.S. Also can someone throw this guy Seamlink under a bus for the comment he made on... "
I realised it was over, a broken heart, I just found out about the loss of a legend. :'(

To her: Get the justice he should have from that 'complication', don't let his death from an error go to waste whatever you do!

**Comment by dominichayesferen** [comment]
@Elbullazul Shall you add me for theme development?
https://github.com/orgs/B00merang-Project/teams/development

**Comment by cinnamoner** [comment]
These r things one is not supposed to talk about. But I've seen a thing or two. I'm a bit older but still qualify for young. Man.

**Comment by ghost** [comment]
RIP

**Comment by cinnamoner** [comment]
@feren issue a request. Can you do code though? That branch is for people who want to deal with code.

**Comment by dominichayesferen** [comment]
@cinnamoner Not really...

**Comment by cinnamoner** [comment]
J'ai pas envie of nothing today.

**Comment by cinnamoner** [comment]
Mate has the advantage of real aero titlebar but the menu sucks. Cinnamon is not capable of real aero titlebar but one has Stark to emulate Vista/7 startmenu. Maddening. Can't someone make a DE capable of both?! Darn.

**Comment by cinnamoner** [comment]
And please don't tell me real aero is obsolete. And have you seen vista expo? With like 50 open and ...

**Comment by cinnamoner** [comment]
So. Where can I find a good menu (Vista/7 style) for Mate?

**Comment by cinnamoner** [comment]
@feren Did you know Michael is teamed up wit Antergos, Ubuntu Mate ... you name it. He has even made a tweak for the boutique to show more apps at once?

**Comment by cinnamoner** [comment]
@Elbullazul Feel free to delete this convo. Doesn't belong.

**Comment by dominichayesferen** [comment]
@cinnamoner That'd be so funny if Muffin got the ability to use another window decorator though...

**Comment by cinnamoner** [comment]
@feren Yeah, for sure. By the way, do you think it's possible for Elbullazul to solve that glow and blue rectangle issue on mouse actions. That's so part of Windows.

**Comment by dominichayesferen** [comment]
Maybe not... (GTK Thing)

**Comment by cinnamoner** [comment]
@feren And Deepin is not a bad concept. But it it should be on Ubuntu. 15.3 that is. Otherwise it's crap. The real one base on Sid is sloooow. And Manjaro's Deepin lacks a software centre and is a twisted Arch offshoot.

**Comment by cinnamoner** [comment]
@feren I have to agree with Dave (Other Stuff). If one's only purpose with an OS is the OS itself, then Arch is a damn good thing :) English Bob replied that Arch is good because it's compiled on your own machine. I don't buy that. Other than the 32/64 aspect, it doesn't matter.

**Comment by cinnamoner** [comment]
@feren Fun fact: I like the Calamares installer because it's got nice colors. Overall looks better than Ubiquity.

**Comment by dominichayesferen** [comment]
@cinnamoner By compiled, I think he meant the installation procedure of installing the base system as a package to the target HDD, etc, etc...

**Comment by cinnamoner** [comment]
@feren Man, I hope we don't upset Elbu with these off-stuff. @Elbullazul Again, please delete this segment.

**Comment by cinnamoner** [comment]
@feren If you could do Arch, would you? Is it worth it? And then when ready, one faulty package can crash down the whole thing. Ubuntu or Arch. Which do you prefer? You know I'm not a big Canonical fan but ... I'm sorry, it works.

**Comment by cinnamoner** [comment]
@feren I would use Debian as a server. But hey, as a daily driver ... no.

**Comment by cinnamoner** [comment]
Mate and Plasma. Those are my favourites atm.

**Comment by cinnamoner** [comment]
No. At this moment in time, Arch vanilla or made easy with an installer (antergos, apricity ... and well Manjaro, which is not really Arch anymore) is not my thing. Although I might be judgemental. Hey, I don't exclude that I might be wrong.

**Comment by cinnamoner** [comment]
@Elbullazul Please delete the ramblings. Sorry.

**Comment by cinnamoner** [comment]
I reinstall windows weakly. Imagine that with Arch. Hahaha.

**Comment by dominichayesferen** [comment]
Nope, apparently not:
https://github.com/linuxmint/Cinnamon/issues/5775#issuecomment-252440354

**Comment by cinnamoner** [comment]
Arch vanilla that is. Or how the hach they call that masochistic procedure when you start out from nothing to build nothing.

**Comment by cinnamoner** [comment]
It's an online install. If one has the misfortune to have a corrupted package ... then ... man I respect people, masochists included. I think Arch lovers enjoy suffering.

**Comment by cinnamoner** [comment]
Hey, I'm just stupid. I don't get Arch and I don't want to either. This is kind of a disclaimer.

**Comment by cinnamoner** [comment]
@Elbullazul Have a good laugh and delete. Sorry.

**Comment by dominichayesferen** [comment]
@Elbullazul You there? Want to add me?
https://github.com/orgs/B00merang-Project/teams/development

**Comment by cinnamoner** [comment]
@Elbullazul Hey, add him. @feren Understand, it's a tremendous responsibility.

Well, Arch is an artform. Like painting, sculpting ... you name it. And there's no practicality to it whatsoever. It's not a tool. It's rather a purpose in itself. If building an OS is your purpose and you don't have any other purposes, than it's awesome. If you want an OS for a tool to pursue other goals than merely the OS, then Arch (which is a culture of its own) is not for you. Don't get me wrong, I've got the deepest respect for Arch people and I appreciate their art. Cause at the end of a day it is a form of digital art, the elusive ultimate goal, and a purpose in itself. I like paintings and sculptures and literature, but none of those are tools. My perception of an OS is that it's gotta be a tool. Lean, mean, efficient and reliable. A tool. Nothing more than a tool. It's gotta be a nice tool but still a tool. Then one uses that tool for whatever his/her goals, purposes. Bottom line: Arch is a form of art. It has no practical purpose whatsoever. A purpose in itself. Like a painting. It starts out of nowhere and is going nowhere.
Again, just my pragmatic view. Never intended to be disrespectful. It's just how I'm seeing it.
Well yeah, one can do things with an Arch distro, true. But that's not at the core of things. At the core of things is this: the OS and then the OS again. It's always about the OS really.


http://youtu.be/29TzwAOiU7s

**Comment by cinnamoner** [comment]
An Arch artist would never look down on an Ubutu user and say he/she is stupid. That kind of thing is done by people who adhere to Arch without understanding what Arch is. They just do it cause they think it's cool. Art is cool indeed but is not for everyone. It takes dedication, sacrifice and suffering. Arch is esoteric. Poetry. It's not a tool. The wave spread by poeple who don't understand Arch is nothing short of a wave of misconceptions.

**Comment by cinnamoner** [comment]
I can never be an Arch man. I can learn Arch but I don't have the drive for it. I completely lack the desire to do Arch. I'm not interested in it. It's not a bad thing but it's not for me. Period.

**Comment by dominichayesferen** [comment]
@cinnamoner What d'ya think?
https://github.com/Elbullazul/Longhorn-Collaboration/issues/8#issuecomment-252494405

**Comment by cinnamoner** [comment]
That was a good thing to close this novel. :)
