### ISSUE TITLE
Longhorn Icons Issues

### ISSUE THREAD

**Issue by brandleesee** [B00merang-Project/Windows-Longhorn#16]
Other icon themes are for comparison.

- Longhorn Pics & Vids icons are the same.
- Longhorn and Adwaita (default) (bash).sh files are the same.

![Adwaita](http://i.imgur.com/ItaBm1D.png)
Adwaita(default)

![Longhorn](http://i.imgur.com/nYZs9vS.png)
Longhorn

![W10](http://i.imgur.com/jDlmhHj.png)
Windows 10

**Comment by brandleesee** [comment]
Longhorn icons are blurred and pixelated.

![](http://i.imgur.com/WvIRpqO.png)
Windows 10

![](http://i.imgur.com/XjPYCWX.png)
Longhorn

![](http://i.imgur.com/RR4Y1xb.png)
Windows 10

![](http://i.imgur.com/b6CVeh4.png)
Longhorn

**Comment by dominichayesferen** [comment]
@brandleesee 
> Longhorn Pics/Vids Icons are the same

That's because they were actually just the 1 library back in Longhorn Builds pre-reset

**Comment by brandleesee** [comment]
@feren I understand. (*and I fixed my own typo!!*) 
@Elbullazul Pics and Vids are separate now so will *new* icons be considered?

**Comment by dominichayesferen** [comment]
@brandleesee There again, there was LH icons (kinda) post-reset in Vista before the green icons (basically when Basic was grey) so we could use those icons for it, and leave the library icons under different names, so that when the time comes for Zuro UI, I could then introduce Libraries...

**Comment by Elbullazul** [comment]
@feren what happened to the pre-reset longhorn icon theme?

http://ferenceo.deviantart.com/art/Sneak-Peek-614272389

**Comment by cinnamoner** [comment]
@Elbullazul The longhorn icons are greatly attenuating the hover-glow displeasure. They are a welcome acquisition. Definitely.

**Comment by cinnamoner** [comment]
Oh, I would love them cover all major desktops (Gnome, Plasma, Cinnamon, Xfce, Mate).

**Comment by dominichayesferen** [comment]
@Elbullazul In essence, the current icon set is pretty much pre-reset

**Comment by cinnamoner** [comment]
@ferns Might write a book about the genesis of Vista and it's sequel (7). I'll have you for consultant.

**Comment by cinnamoner** [comment]
@feren Might write a book about the genesis of Vista and it's sequel (7). I'll have you for consultant.

**Comment by brandleesee** [comment]
This is too old now. Would need re-testing. Should this happen will open a new issue because of testing on a more modern system.
