### ISSUE TITLE
Migrate to Cinnamon 4

### ISSUE THREAD

**Issue by dominichayesferen** [B00merang-Project/Windows-Longhorn#17]
Running the latest of the themes on Cinnamon 3.2, and either the menus are white, or have no background whatsoever...

To fix:

- Make all the pre-reset + 5048 one's menus look like GTK Menus, and add CinnVIIStarkMenu Support
- Make the post-reset menus look like what you get in Vista...

**Comment by Elbullazul** [comment]
Implemented this weekend
