### ISSUE TITLE
Jade Progress

### ISSUE THREAD

**Issue by dominichayesferen** [B00merang-Project/Windows-Longhorn#3]
@Guys
This is how far I've got with that Basic (Jade) theme and icon set:
![screenshot from 2016-06-08 20-59-32](https://cloud.githubusercontent.com/assets/11057934/15909277/75de2b80-2dbd-11e6-89d0-6747b72d58d2.png)

**Comment by Elbullazul** [comment]
looks good,

I had never seen that icon set...

**Comment by dominichayesferen** [comment]
The icon set is half Longhorn Skin Pack, half 4074, half XP

**Comment by cinnamoner** [comment]
> It's  half  Longhorn Skin Pack, half 4074, half XP

@ferns
1/2 + 1/2 +1/2 = 1.5
That's a whole theme and a half. Just kidding. Looks very pretty.

**Comment by dominichayesferen** [comment]
...almost forgot, and it's "half" Longhorn Linux icons

**Comment by cinnamoner** [comment]
= 2 hehe.

**Comment by cinnamoner** [comment]
@feren 
Why have you locked Plex?

**Comment by dominichayesferen** [comment]
To then make it just for archive reasons and prevent anyone else deleting them, etc by accident (mainly for archive reasons)...

PS: Aren't you a Collaborator? Collabs can edit and comment on Locked Conversations afterall...

It also makes it easier for @Elbullazul if it's left as it is... (Access to resource wise)

**Comment by cinnamoner** [comment]
@feren 
No, I cannot comment on Plex. For whatever reason, I'm locked out as well.

**Comment by cinnamoner** [comment]
@feren 
I've just checked again.


> Feren locked and limited conversation to collaborators 18 hours ago.

**Comment by cinnamoner** [comment]
@feren 
No big deal though.

**Comment by cinnamoner** [comment]
@feren 
Inasmuch as it's a resource archive, you're correct. Nothing good comes from pointless overcommentin.

**Comment by dominichayesferen** [comment]
The Jade theme is now pushed into the Repo... Issue Closed

**Comment by Elbullazul** [comment]
@feren do you mind if I remaster the cinnamon theme?

**Comment by dominichayesferen** [comment]
No, not at all, as long as you don't replace the other one if it doesn't look like that proper Longhorn build's Aero taskbar... (Send a screenshot?)
