### ISSUE TITLE
Plex Resources

### ISSUE THREAD

**Issue by dominichayesferen** [B00merang-Project/Windows-Longhorn#4]
Just so everyone's prepared for when Plex 2.0 is done, here's most of the resources: (Just remove the pink like usual)
![button0active](https://cloud.githubusercontent.com/assets/11057934/15971060/b217fcd4-2f2f-11e6-8c51-b162c4d9c9f7.png)
![button0inactive](https://cloud.githubusercontent.com/assets/11057934/15971061/b218e86a-2f2f-11e6-8d3b-aaf4d0f53555.png)
![button1active](https://cloud.githubusercontent.com/assets/11057934/15971063/b21c0ad6-2f2f-11e6-8d4a-15dfc0e840b6.png)
![button1inactive](https://cloud.githubusercontent.com/assets/11057934/15971062/b21b2832-2f2f-11e6-8cf4-9d77779dfc11.png)
![button1pressedactive](https://cloud.githubusercontent.com/assets/11057934/15971064/b21e584a-2f2f-11e6-9a75-c6a9bb960464.png)
![button1pressedinactive](https://cloud.githubusercontent.com/assets/11057934/15971065/b22039e4-2f2f-11e6-90c2-440f9088ca2c.png)
![button2active](https://cloud.githubusercontent.com/assets/11057934/15971068/b235b4e0-2f2f-11e6-9c0c-399ea9f613dc.png)
![button2inactive](https://cloud.githubusercontent.com/assets/11057934/15971066/b22e932c-2f2f-11e6-9442-d02d3c544255.png)
![button3active](https://cloud.githubusercontent.com/assets/11057934/15971070/b237471a-2f2f-11e6-9fa9-9b7352834023.png)
![button3inactive](https://cloud.githubusercontent.com/assets/11057934/15971067/b23516ac-2f2f-11e6-999c-b322b3b6b4f0.png)
![checkboxnew](https://cloud.githubusercontent.com/assets/11057934/15971069/b23679ca-2f2f-11e6-8603-426fbe2bf7fa.png)
![classicrestorebutton](https://cloud.githubusercontent.com/assets/11057934/15971071/b2406a66-2f2f-11e6-8420-bfe866fb56d8.png)
![closetoolbutton](https://cloud.githubusercontent.com/assets/11057934/15971073/b24b12fe-2f2f-11e6-873d-a387436aa15f.png)
![closetoolbuttonglyph](https://cloud.githubusercontent.com/assets/11057934/15971072/b248ddc2-2f2f-11e6-8bc4-bda35eeff256.png)
![comboboxdropdownbutton](https://cloud.githubusercontent.com/assets/11057934/15971074/b24d3d90-2f2f-11e6-9064-f7c4fab923d0.png)
![comboboxdropdownglyph](https://cloud.githubusercontent.com/assets/11057934/15971076/b250ac96-2f2f-11e6-9382-693f83d30791.png)
![extraimages](https://cloud.githubusercontent.com/assets/11057934/15971075/b24efefa-2f2f-11e6-995a-8228da62ce49.png)
![groupboxedge](https://cloud.githubusercontent.com/assets/11057934/15971077/b25b439a-2f2f-11e6-84ab-80e0f889488d.png)
![listviewheader](https://cloud.githubusercontent.com/assets/11057934/15971078/b25dc9d0-2f2f-11e6-9fd9-0d504af5b2a3.png)
![mdibuttons](https://cloud.githubusercontent.com/assets/11057934/15971079/b263c3f8-2f2f-11e6-827f-e11f5ef12ac3.png)
![menubackground](https://cloud.githubusercontent.com/assets/11057934/15971080/b264a9a8-2f2f-11e6-9a51-6fe782a7bd61.png)
![menubar](https://cloud.githubusercontent.com/assets/11057934/15971082/b269d2d4-2f2f-11e6-9740-f07f062da7a3.png)
![menubaritem](https://cloud.githubusercontent.com/assets/11057934/15971081/b267767e-2f2f-11e6-8f37-86d8de075e3c.png)
![menuitem](https://cloud.githubusercontent.com/assets/11057934/15971084/b273f5ac-2f2f-11e6-84fc-2788443cf6ba.png)
![plexm6barprogressbarxp](https://cloud.githubusercontent.com/assets/11057934/15971085/b27614fe-2f2f-11e6-90c1-1bcc056d246a.png)
![plexm6barprogressbarxpvert](https://cloud.githubusercontent.com/assets/11057934/15971086/b2792d7e-2f2f-11e6-829d-4df09ee7afea.png)
![plexm6barprogresschunkxp](https://cloud.githubusercontent.com/assets/11057934/15971087/b27af456-2f2f-11e6-9d37-8edd1ee93965.png)
![plexm6barprogresschunkxpvert](https://cloud.githubusercontent.com/assets/11057934/15971088/b27c8e56-2f2f-11e6-8e4f-bda0b291af17.png)
![progressbar](https://cloud.githubusercontent.com/assets/11057934/15971089/b2816bb0-2f2f-11e6-9f93-fedd229939e0.png)
![pushbutton](https://cloud.githubusercontent.com/assets/11057934/15971095/b298fe6a-2f2f-11e6-8522-5b07a186e827.png)
![radiobuttonnew](https://cloud.githubusercontent.com/assets/11057934/15971092/b290b2aa-2f2f-11e6-9a55-a70285116261.png)
![rebar](https://cloud.githubusercontent.com/assets/11057934/15971090/b28e0974-2f2f-11e6-87ae-edfe3ba94bd4.png)
![rebargripper](https://cloud.githubusercontent.com/assets/11057934/15971091/b2904a0e-2f2f-11e6-8d5d-6a9dde271949.png)
![scrollbararrows](https://cloud.githubusercontent.com/assets/11057934/15971093/b29260aa-2f2f-11e6-90a9-e121f5b98705.png)
![scrollbararrowsglyph](https://cloud.githubusercontent.com/assets/11057934/15971094/b29659f8-2f2f-11e6-9610-a026e5fa4eab.png)
![scrollbargripperhorzdot](https://cloud.githubusercontent.com/assets/11057934/15971096/b2a3bfb2-2f2f-11e6-971d-6119dfc793a0.png)
![scrollbargrippervertdot](https://cloud.githubusercontent.com/assets/11057934/15971097/b2a61fa0-2f2f-11e6-9f76-950d0d6fbf06.png)
![scrollbarshafthorz](https://cloud.githubusercontent.com/assets/11057934/15971098/b2ad62ce-2f2f-11e6-93e6-e051e7f4fd54.png)
![scrollbarshaftvert](https://cloud.githubusercontent.com/assets/11057934/15971100/b2adf194-2f2f-11e6-9a0e-53bb5a5fdf82.png)
![scrollbarthumbbtnhorz](https://cloud.githubusercontent.com/assets/11057934/15971101/b2ae93d8-2f2f-11e6-9e30-b6f22b86cc99.png)
![scrollbarthumbbtnvert](https://cloud.githubusercontent.com/assets/11057934/15971099/b2ada536-2f2f-11e6-9b03-f1add995d32a.png)
![spinupdownhorizontal](https://cloud.githubusercontent.com/assets/11057934/15971102/b2b9b006-2f2f-11e6-9526-0c96c2b2ea9d.png)
![spinupdownhorizontalglyph](https://cloud.githubusercontent.com/assets/11057934/15971103/b2c25c6a-2f2f-11e6-86c0-947ac03ae374.png)
![spinupdownvertical](https://cloud.githubusercontent.com/assets/11057934/15971106/b2c80aca-2f2f-11e6-90c4-16f3c95d1528.png)
![spinupdownverticalglyph](https://cloud.githubusercontent.com/assets/11057934/15971105/b2c7a120-2f2f-11e6-8fa4-a419eb6b459d.png)
![startmenugroupback](https://cloud.githubusercontent.com/assets/11057934/15971104/b2c5e6a0-2f2f-11e6-85ca-5b92ace7300a.png)
![startmenutoolbarbutton](https://cloud.githubusercontent.com/assets/11057934/15971107/b2c84800-2f2f-11e6-986a-8f2500bc38d8.png)
![startpanellogoff](https://cloud.githubusercontent.com/assets/11057934/15971108/b2d06242-2f2f-11e6-9780-11c30fb3988e.png)
![startpanelmoreprogarrow](https://cloud.githubusercontent.com/assets/11057934/15971114/b2fa756e-2f2f-11e6-857a-27e960e4e6db.png)
![startpanelmoreprogback](https://cloud.githubusercontent.com/assets/11057934/15971111/b2e12654-2f2f-11e6-898e-80ff0fd9c17b.png)
![startpanelplaceslist](https://cloud.githubusercontent.com/assets/11057934/15971110/b2df3efc-2f2f-11e6-9ee9-bcb6afd508e2.png)
![startpanelplaceslistsep](https://cloud.githubusercontent.com/assets/11057934/15971113/b2e51caa-2f2f-11e6-86d4-4ffa3994e06a.png)
![startpanelproglist](https://cloud.githubusercontent.com/assets/11057934/15971109/b2dfcb42-2f2f-11e6-8bb5-a4ed18bca7d0.png)
![startpanelproglistsep](https://cloud.githubusercontent.com/assets/11057934/15971112/b2e3b81a-2f2f-11e6-8434-a95e9e978b9f.png)
![startpaneluserpane](https://cloud.githubusercontent.com/assets/11057934/15971118/b2fe3e92-2f2f-11e6-87c3-e1b3d8290aa3.png)
![startpaneluserpicture](https://cloud.githubusercontent.com/assets/11057934/15971119/b302d2ae-2f2f-11e6-80e3-f155aa3f7cb6.png)
![statusbar](https://cloud.githubusercontent.com/assets/11057934/15971115/b2fac2a8-2f2f-11e6-80e9-4cef511b994f.png)
![sunkedge](https://cloud.githubusercontent.com/assets/11057934/15971117/b2fd2912-2f2f-11e6-8852-cff89b7d650b.png)
![tabitem](https://cloud.githubusercontent.com/assets/11057934/15971116/b2fbfa10-2f2f-11e6-8f19-e2fef2733bed.png)
![tabpane](https://cloud.githubusercontent.com/assets/11057934/15971120/b310ff46-2f2f-11e6-96c7-60abca702963.png)
![tabspage](https://cloud.githubusercontent.com/assets/11057934/15971121/b3182d8e-2f2f-11e6-8e1c-fbaca1fbf8f0.png)
![taskbandgroupback](https://cloud.githubusercontent.com/assets/11057934/15971123/b318baf6-2f2f-11e6-980e-4d5e863d411c.png)
![taskbandgroupmenuitem](https://cloud.githubusercontent.com/assets/11057934/15971125/b31cb03e-2f2f-11e6-953f-035311cd69f2.png)
![taskbandtoolbarbtn](https://cloud.githubusercontent.com/assets/11057934/15971122/b318acfa-2f2f-11e6-8fff-9cb0fa9cc5de.png)
![taskbandtoolbarbtnvert](https://cloud.githubusercontent.com/assets/11057934/15971124/b31b5dba-2f2f-11e6-9908-199f92762cfa.png)
![taskbarbackground](https://cloud.githubusercontent.com/assets/11057934/15971126/b32ba102-2f2f-11e6-8b49-376b82ce64f2.png)
![taskbarbackgroundvert](https://cloud.githubusercontent.com/assets/11057934/15971131/b340d158-2f2f-11e6-993f-5a05a59ffe54.png)
![taskbarflashingbutton](https://cloud.githubusercontent.com/assets/11057934/15971128/b33687c0-2f2f-11e6-8eac-901260d5da76.png)
![taskbarquicklaunch](https://cloud.githubusercontent.com/assets/11057934/15971130/b337b906-2f2f-11e6-8f17-d5c22abfc34a.png)
![taskbarquicklaunchv](https://cloud.githubusercontent.com/assets/11057934/15971127/b332306c-2f2f-11e6-94b8-195ad4393294.png)
![taskbarrebargripper](https://cloud.githubusercontent.com/assets/11057934/15971129/b3371d52-2f2f-11e6-808d-c02609f12c14.png)
![taskbarrebargrippervert](https://cloud.githubusercontent.com/assets/11057934/15971133/b34e0b2a-2f2f-11e6-8b22-f69f6b58a3c9.png)
![taskbarsizingbar](https://cloud.githubusercontent.com/assets/11057934/15971132/b3477a30-2f2f-11e6-8fda-ba1b8727e725.png)
![taskbarsizingbarvert](https://cloud.githubusercontent.com/assets/11057934/15971134/b34f0cbe-2f2f-11e6-8de6-48b3c933ef55.png)
![taskbarstartbutton](https://cloud.githubusercontent.com/assets/11057934/15971135/b3515410-2f2f-11e6-822b-9846a34a397c.png)
![toolbarbutton](https://cloud.githubusercontent.com/assets/11057934/15971136/b353aef4-2f2f-11e6-9f7a-6d852f26c653.png)
![trackbarthumbdown](https://cloud.githubusercontent.com/assets/11057934/15971137/b35884ce-2f2f-11e6-863a-2f1a009f5752.png)
![trackbarthumbhorz](https://cloud.githubusercontent.com/assets/11057934/15971138/b35c23cc-2f2f-11e6-88d1-44c425012812.png)
![trackbarthumbleft](https://cloud.githubusercontent.com/assets/11057934/15971140/b36c8816-2f2f-11e6-8c67-c5568a228349.png)
![trackbarthumbright](https://cloud.githubusercontent.com/assets/11057934/15971142/b36e6dd4-2f2f-11e6-8cba-b89a22c71ca8.png)
![trackbarthumbup](https://cloud.githubusercontent.com/assets/11057934/15971139/b368b52e-2f2f-11e6-99d1-0393fcff6eb6.png)
![trackbarthumbvert](https://cloud.githubusercontent.com/assets/11057934/15971141/b36c96a8-2f2f-11e6-865a-c6bbedee7865.png)
![trackbartrack](https://cloud.githubusercontent.com/assets/11057934/15971144/b371053a-2f2f-11e6-9879-b181e5c40b42.png)
![trackbartrackvert](https://cloud.githubusercontent.com/assets/11057934/15971143/b3702a20-2f2f-11e6-8c4f-21051969fde5.png)
![traynotifyhorzarrow](https://cloud.githubusercontent.com/assets/11057934/15971145/b38303f2-2f2f-11e6-9d94-2e15a50f0608.png)
![traynotifyvertarrow](https://cloud.githubusercontent.com/assets/11057934/15971147/b384c5ac-2f2f-11e6-8d63-af628543213a.png)
![treeviewnode](https://cloud.githubusercontent.com/assets/11057934/15971146/b38474bc-2f2f-11e6-9c7c-9d84b1707e05.png)
![windowframebottomuis2](https://cloud.githubusercontent.com/assets/11057934/15971150/b38cd008-2f2f-11e6-8ee6-211a5409c8db.png)
![windowframeleftuis2](https://cloud.githubusercontent.com/assets/11057934/15971148/b3868e64-2f2f-11e6-95de-6e717093734a.png)
![windowframerightuis2](https://cloud.githubusercontent.com/assets/11057934/15971149/b38c6708-2f2f-11e6-9251-7af6ac4ede07.png)
![windowframetoolcaption](https://cloud.githubusercontent.com/assets/11057934/15971151/b39a814e-2f2f-11e6-9e0c-3ceeb8a181db.png)
![windowframetoolhorizontal](https://cloud.githubusercontent.com/assets/11057934/15971154/b3a2d92a-2f2f-11e6-8ba2-f18b2cf88a18.png)
![windowframetoolvertical](https://cloud.githubusercontent.com/assets/11057934/15971152/b39aef62-2f2f-11e6-9416-f8b8130ac3fe.png)
![windowframetopuis2](https://cloud.githubusercontent.com/assets/11057934/15971153/b39c7260-2f2f-11e6-9dc6-006b6cb2c787.png)

**Comment by dominichayesferen** [comment]
Or you could just use the resources here (Pink removing needed) :
https://onedrive.live.com/redir?resid=FDBB94FEC377D26B!905&authkey=!AHCiFX3X-v2p7R0&ithint=folder%2cpng

**Comment by dominichayesferen** [comment]
...Oh and also, here's some SLATE Resources:
![image](https://cloud.githubusercontent.com/assets/11057934/15971308/5f34ab74-2f30-11e6-925d-1a3ccf7a46f2.png)

**Comment by Elbullazul** [comment]
Oh cool.  For the next resources,  would you please zip them and upload the zip instead? It will take less time to process

**Comment by dominichayesferen** [comment]
Look at the link under Plex, it has a OneDrive archive that upon download, zips up...
