### ISSUE TITLE
Aero Progress

### ISSUE THREAD

**Issue by dominichayesferen** [B00merang-Project/Windows-Longhorn#5]
...and here's Aero so far (trying to fix the buttons though...)
![screenshot from 2016-06-11 16-35-47](https://cloud.githubusercontent.com/assets/11057934/15985885/e69c7052-2ff2-11e6-80cb-e2de330290d9.png)

**Comment by dominichayesferen** [comment]
The titlebars are based off of "Express" in Vista Beta 2:
http://www.betaarchive.com/imageupload/2015-05/1430489973.or.97007.png

**Comment by cinnamoner** [comment]
@feren 
I like very much the titlebars and buttons of "Express" in Vista Beta 2. As a Matter of fact, I pretty much like everything about the Beta 2, but the "Express" is the coolest. Period.

**Comment by cinnamoner** [comment]
@feren
Point me to a beta 2 iso, will you. I wanna check it out thoroughly.

**Comment by dominichayesferen** [comment]
https://winworldpc.com/product/windows-longhorn-vis/post-reset

Hit "Build 5456" as it's one that I know has the Old Windows Basic theme... Then download it and install in a VM I guess...

**Comment by cinnamoner** [comment]
@feren 
Yeah, but all the screenshots you've posted represent build 5270. !?

**Comment by cinnamoner** [comment]
@feren 
So if I don't run in VM the machine could go kaboom or what?

**Comment by dominichayesferen** [comment]
Who knows? If 5456 glitched like that, you'd probably go nuts yourself trying to make it completely fully work, not forgetting the glitches and bugs, etc. (Vista has a bad reputation for RTM, this is probably worse than RTM for it)

**Comment by cinnamoner** [comment]
@feren 
"Expess". That's the one I like.

**Comment by cinnamoner** [comment]
@feren 
I know this is not border issue, but do you think those blue navigation buttons enbeded in those pits could pe replicated as well? If unclear, please ask.

**Comment by dominichayesferen** [comment]
Might be possible, if one makes an alternative File Manager fork where back and forward are just on their own and without the Button BG (otherwise it would cause problems with other buttons)

One did do that before (elementary Files), but the pits weren't possible though in that one...

**Comment by dominichayesferen** [comment]
Hmm, not sure at all what's happening with @Elbullazul , whether he's been kicked from his computer (again), or something else... :/

**Comment by cinnamoner** [comment]
@feren 
He'll show. I guess he wantsta take us by surprise.

**Comment by Elbullazul** [comment]
Hi guys,  sorry for the delay.  Glad to see everything has advanced so well.

**Comment by dominichayesferen** [comment]
Hey @Elbullazul , if you could do it, could you get StarkMenu to work properly on this Start Menu BG? (It's called Hillel Start Menu)

![menu-bg](https://cloud.githubusercontent.com/assets/11057934/16014575/a80aee16-3189-11e6-8f2d-61e739c9c372.png)

(and once you do, could you merge it into Aero's cinnamon folder over it's current menu-bg.png file?)

**Comment by cinnamoner** [comment]
?!

**Comment by dominichayesferen** [comment]
Bug fixing progress:
![screenshot from 2016-07-23 14-53-07](https://cloud.githubusercontent.com/assets/11057934/17078521/3c9d0d82-50e5-11e6-93ff-13efe23f2130.png)

**Comment by cinnamoner** [comment]
@feren 
Bring it from from thread 49, W10 repo to righ here. Please and thank you!

**Comment by cinnamoner** [comment]
@feren 
Okay. Where's it?

**Comment by cinnamoner** [comment]
I've already spent more hours on Git than Elbu himself.

**Comment by cinnamoner** [comment]
It's in the zip then. I won't put all my cores into it.

**Comment by dominichayesferen** [comment]
Ah oops, I put it on "Just chatting to each other (friends)"

**Comment by cinnamoner** [comment]
I'm here.

**Comment by cinnamoner** [comment]
@feren 
I'm here.

**Comment by cinnamoner** [comment]
@feren 
Here I am

**Comment by cinnamoner** [comment]
@feren 
Tell me about Express.

**Comment by cinnamoner** [comment]
@feren 
No rush. I'll be having coffee. Just nice and slow

**Comment by dominichayesferen** [comment]
It'll probably be updated tommorow to that one

Basically, Aero Express since day one has just been a version of Aero Microsoft planned along with Windows Longhorn, IE7, etc. It ended up being in the first released post-reset build using registry keys to modify the Aero mode DWM used to Express, also where the name comes from, and then it re-appeared in a later build (that I can't remember the build number of but is the inspiration for this Aero theme (titlebar-bg wise)) simply under the name of "Express" in the Appearance dialog (along with "Basic" and "Glass") that, if you had a DWM-compatible PC, would end up giving you that theme you saw in that build screenshot of it, but then after that, it all just disappeared... or did it? That was just it's first chapter. Windows Vista Home Basic was to be released with the Vista product line and work already started on it bringing a unique newcomer to the theme list, "Standard". Unlike previous builds, Aero Standard had been the rebirth of Express replacing Glass in that version of Vista with a theme with absolutely NO transparency whatsoever. Then came Windows 7... Windows 7 Home Basic, nothing had changed when it came to the existence of Standard and like its predecesor, this Standard was on by default, unchangable and simply lacking transparency everywhere. But, then, Microsoft made Windows 8, first it was Windows 8 M3 Leaked Builds with promising features THAT NEVER MADE IT TO DEV PREVIEW NEVERMIND RTM such as "User Tile" on the taskbar, "Animated Tiles" (Tiles were the name given to User Pictures in those builds), the Explorer Ribbon, and a new looking Login Screen showing very early signs of Windows 8 having a Tablet Mode instead of 10 (the Start Menu could've been in Windows 8 if it wasn't for MS forgetting about a Tablet Mode, then, RTM Builds, something terrible had happened, AERO WAS NO LONGER AERO. In the last minute, Microsoft ditched Aero Transparency forever in Windows 8.X and Windows 10 as we know it. The only Aero left, a hybrid between Aero Standard and Aero Glass. Aero Standard lived on as the default in ALL Windows 8.x/10 versions as a decoration for the window borders by default whilst Aero was just left there to decorate the rest. It could've even had blur in Windows 10 on the taskbar/start but guess what? Microsoft brung it into a Win10 Preview Build only to then say it "has hardware problems" and then they removed it completely NEVER TO BE SEEN AGAIN. Aero Express was and still though is a mystery to many in what it was to achieve in its existence in Longhorn RTM'd...

**Comment by cinnamoner** [comment]
@feren 
Thanks.

**Comment by Elbullazul** [comment]
well, had some spare time this weekend...

![screenshot_2016-11-05_21-38-23](https://cloud.githubusercontent.com/assets/15310985/20055862/49b70188-a4b1-11e6-8eff-2cd527fbcdae.png)
![screenshot_2016-11-05_22-59-04](https://cloud.githubusercontent.com/assets/15310985/20055863/49b96ed2-a4b1-11e6-963f-cef46d2adf80.png)

**Comment by Elbullazul** [comment]
so aero is ready too :D

**Comment by dominichayesferen** [comment]
@Elbullazul 
1. Nice
2. Can you make the buttons touch the top of the titlebar in the metacity? (I did that myself, but I lost that (I think) when the HDD died)
3. For the headerbars, since you can't move them:
- For the close button, make the top-right corner round like the bottom-right corner is
- For the minimize button, make the top-left corner round too

Or if you can't make the buttons connect to each other in GTK Headerbars:
Make **all of the corners** of **all of the titlebar buttons** the **same roundness** as each other

**Comment by Elbullazul** [comment]
last lines means that if I can't reduce spaces, make them look like regular aero?

**Comment by dominichayesferen** [comment]
@Elbullazul Last lines mean that if you want reduce spaces, make all the button corners the same amount of rounding from the other rounded corners...

**Comment by cinnamoner** [comment]
@Elbullazul Aero is cool :D

**Comment by cinnamoner** [comment]
@feren @Elbullazul Meh. The buttons look good. Like them as they are.

@feren But hey, de gustibus non disputandum 🗡:D

**Comment by dominichayesferen** [comment]
@Elbullazul I was just thinking it'd look odd for the buttons to be floating like that while looking like they should be at the top of the bar with no spacing...

**Comment by Elbullazul** [comment]
@feren I'll have a look at the metacity theme...

**Comment by dominichayesferen** [comment]
@Elbullazul I was meaning the Headerbars...

**Comment by Elbullazul** [comment]
oh, yeah, they look totally out of place, but until feren os switches to gtk 3.20, those buttons are screwed over there because of padding & margins (not tweakable)

**Comment by dominichayesferen** [comment]
@Elbullazul More like until LM does... (Linux Mint controls the GTK version)

**Comment by Elbullazul** [comment]
switch to arch O_O

**Comment by dominichayesferen** [comment]
@Elbullazul Nah, don't know how to package to repositories properly... :/

**Comment by dominichayesferen** [comment]
...also, feren GTK is as good as BROKEN in 3.20... :/

**Comment by dominichayesferen** [comment]
@Elbullazul This is what I mean by 'rounding':
![screenshot from 2016-11-12 15-06-33](https://cloud.githubusercontent.com/assets/11057934/20238713/9dbca350-a8e9-11e6-8f93-1a37dc06aa84.png)
(That makes it look less out-of-place when GTK separates the buttons)
Also, what happened to Non-CSB?

**Comment by dominichayesferen** [comment]
@Elbullazul I also noticed a problem with the latest Aero update:
The category text looks really bad in StarkMenu (should be while instead of black)

**Comment by dominichayesferen** [comment]
...either that, or have the menu box expand into the categories

**Comment by cinnamoner** [comment]
@feren I have a third eye, so I knew what you meant by rounding.

**Comment by cinnamoner** [comment]
@feren Oh my Goodness. Just read through that solid block of text. You should write a book titled *Longhorn*. You have my blessing (should you need it).

**Comment by cinnamoner** [comment]
Just between you and me, 7 is a continuation of Longhorn. Last time I checked, Vista and 7 were basically on the same kernel :)

**Comment by cinnamoner** [comment]
@feren @Elbullazul The gtk versioning thing from our beloved Gnome team is a nightmare to me. Ugh!

**Comment by Elbullazul** [comment]
@feren I thought I had pushed a rounded icons version, maybe should re-check...

what happened to non-CSB? what do you mean? I haven't applied changes yet, because I don't run them as daily themes, because I love it CSB :/ I'll update them soon enough.

**Comment by dominichayesferen** [comment]
@Elbullazul On the Releases, Non-CSB is missing...

**Comment by Elbullazul** [comment]
@feren like I said, haven't applied changes to non-CSB yet

**Comment by dominichayesferen** [comment]
Well, nevermind, I patched non-CSB

BTW, I noticed a regression:
The categories are quite unreadable on StarkMenu in Aero now...

**Comment by Elbullazul** [comment]
fixed
