### ISSUE TITLE
Plex Progress(?)

### ISSUE THREAD

**Issue by dominichayesferen** [B00merang-Project/Windows-Longhorn#6]
Was bored so I decided to start Plex in Cinnamon, this is what it looks like right now with StarkMenu:
![plex](https://cloud.githubusercontent.com/assets/11057934/15990738/1d01631c-3095-11e6-87ad-a05ba323ac98.png)

**Comment by cinnamoner** [comment]
@feren 
Same here. Reminiscent of XP, but it's supposed to be that way, I guess.

**Comment by ghost** [comment]
@feren set the color in the box and not in the menuitems on cinnamon.please try without asking...

**Comment by dominichayesferen** [comment]
@bluedxca93 , could you tell me where in the file that colour code to change is to make it much easier to do?
@cinnamoner , who knows? Just a quick change to @Elbullazul 's Vista Theme and then replacing a few window buttons and it will be a bonus like Beta 1 (non-Aero) and Plex 1.0

**Comment by ghost** [comment]
cinnamon.css remove color code from favorites menuitem and set it in box, do the same for menu and applications.

**Comment by Elbullazul** [comment]
Very nice.  Except that stark can't dual color text very well.  I'll be back when I get to use my pc

**Comment by Elbullazul** [comment]
@feren here's progress on the GTK theme : 
![capture du 2016-06-16 14 09 24](https://cloud.githubusercontent.com/assets/15310985/16127793/f551f27a-33cb-11e6-9533-15b9e8c83ba5.png)

**Comment by dominichayesferen** [comment]
OMG Nice!
Just some problems:
- Windows Classic is not the button scheme of Plex
- Wrong button theme in GTK

PS: I was meaning to do Plex 2.0 (which is the one that you see in Longhorn 4039 (not worth installing, I've been told it's the slowest Windows build ever (5 mins to boot on new install, etc))

**Comment by dominichayesferen** [comment]
Do you mind if when my Metacity and Cinnamon are ready, if I push them and move the current one to the bonus Plex 1.0 one (it looks like Plex 1.0 with the gradient)?

**Comment by dominichayesferen** [comment]
Actually, I'll just push Plex Cinnamon in it's current state once I get the applet and window list buttons to be their Plex ones then work on 2.0 Metacity (see how mine and yours compare)...

**Comment by feren** [comment]
@Elbullazul 
How do you set up Git for Linux to work on my account? (I've tried to set it up to no avail)

**Comment by Elbullazul** [comment]
@feren all right!

P.S. is this what you meant?

![Windows Longhorn 4039](http://longhorn.ms/wp-content/uploads/4039-dwm.png)

**Comment by dominichayesferen** [comment]
@Elbullazul 
Yeah but without the Aero prototype... :P

**Comment by ghost** [comment]
good work.
my favorite idea to make at least a theme of is watercolor.
Can someone make something similar to these info a metacity theme?
www.windows-nation.de/whistler2416/whistlerbeta1.html
The rest isn't worth doing anything with it

**Comment by Elbullazul** [comment]
@bluedxca93 probably will,  in some time.  

If looks like ms took Windows 3 and 95 and blended everything xd

**Comment by Elbullazul** [comment]
@feren i'll change the buttons,  I just wanted to get the gtk theme started. 

Wrong button style? What do you mean?

**Comment by dominichayesferen** [comment]
The gradients look odd and out of place for the buttons, the buttons themselves are lighter coloured, eg:
![image](https://cloud.githubusercontent.com/assets/11057934/16155223/43f54596-34a6-11e6-8b60-44089929505e.png)

(IN ABOUT WINDOWS WINDOW)

**Comment by Elbullazul** [comment]
@feren all right I'll fix it

**Comment by dominichayesferen** [comment]
Plex Cinnamon is now here.

**Comment by Elbullazul** [comment]
amazing work!

**Comment by dominichayesferen** [comment]
Now for metacity... ;P
WIP:  ![screenshot from 2016-06-22 18-23-07](https://cloud.githubusercontent.com/assets/11057934/16276473/6c24c0a6-38a6-11e6-99e0-e9b894fefd57.png)

**Comment by Elbullazul** [comment]
is it how it looks? or is it the royal variant?

plex looks so much like luna/royale at times...

**Comment by dominichayesferen** [comment]
Everything but the window buttons are Plex, the window buttons are Royale... (Hence, WIP)

(It even has exact sizes to Luna/Royale Metacity Themes making doing it properly much easier...)
For reference, take a look at the image above of 4039

**Comment by cinnamoner** [comment]
@feren 
Like it.

**Comment by dominichayesferen** [comment]
About to push Metacity to the repo...

PS: The current one WILL be overwritten (it has the wrong buttons for the theme)

**Comment by dominichayesferen** [comment]
Is it done, now no more need to keep this issue open... Case Closed.

**Comment by Elbullazul** [comment]
![screenshot_2016-10-01_21-49-56](https://cloud.githubusercontent.com/assets/15310985/19018040/28711074-8821-11e6-8cbe-0df3d902baf7.png)

**Comment by dominichayesferen** [comment]
@Elbullazul You may want to fix up the gradient on the headers on non-CSD apps a bit...

**Comment by Elbullazul** [comment]
like what apps?

**Comment by dominichayesferen** [comment]
Cinnamon Settings

**Comment by Elbullazul** [comment]
haven't pushed changes yet

**Comment by dominichayesferen** [comment]
@Elbullazul Did you get the resources for Jade all right?

**Comment by Elbullazul** [comment]
can't find the picture now :/

please repost in the #13 thread

thanks

**Comment by Elbullazul** [comment]
ready to port to 3.20...
