### ISSUE TITLE
Slate Progress

### ISSUE THREAD

**Issue by dominichayesferen** [B00merang-Project/Windows-Longhorn#7]
...and I've also started Slate, this is it so far (out of boredom)
![slate](https://cloud.githubusercontent.com/assets/11057934/15991112/07492d6e-30a1-11e6-803b-65f973c8e8fd.png)

**Comment by cinnamoner** [comment]
@feren 
This one looks good too. Perhaps a little reminiscent of XP (so is Jade). But they are supposed to be that  way.

**Comment by Elbullazul** [comment]
cool! :D

**Comment by dominichayesferen** [comment]
@cinnamoner @Elbullazul 
Making HUGE Progess on Metacity, here's a sneak preview of it so far: (It's the exact same titlebar height as Longhorn!)
![screenshot from 2016-08-11 15-26-09](https://cloud.githubusercontent.com/assets/11057934/17591891/a369f888-5fcf-11e6-8f21-f520ae79cbd6.png)

**Comment by dominichayesferen** [comment]
Nearly there, just goanna now reboot into Windows to push this baby to the repository.

**Comment by feren** [comment]
Ok, about to push Cinnamon's Windows Longhorn Slate theme to master, after that, your turn @Elbullazul (With the Slate GTK)...

**Comment by dominichayesferen** [comment]
Slate is now complete with a Cinnamon and Metacity theme, personally, I'm prouder of the parts of this theme than of the parts of other themes that I made for Longhorn Collaboration (apart from Aero, that's still cooler)... :)

**Comment by dominichayesferen** [comment]
...Your turn @Elbullazul to do GTK 2/3 Slate Themes. (After Windows 10 1.0.0)

**Comment by cinnamoner** [comment]
@feren Yeah, absolutely, Slate is a cutie. Metacity looking good.🆒
